/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.unifio.projetointegrador.formularios;

import br.edu.unifio.projetointegrador.entidades.Categoria;
import io.ebean.DB;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CategoriaForm extends javax.swing.JDialog {

    /**
     * Creates new form CategoriaForm
     */
    public CategoriaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotuloCodigo = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JTextField();
        rotuloNome = new javax.swing.JLabel();
        textoNome = new javax.swing.JTextField();
        selecaoAtivo = new javax.swing.JCheckBox();
        botaoIncluir = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        rolagemCategorias = new javax.swing.JScrollPane();
        tabelaCategorias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Categorias");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        rotuloCodigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotuloCodigo.setText("Código");

        textoCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        rotuloNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotuloNome.setText("Nome");

        textoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        selecaoAtivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        selecaoAtivo.setSelected(true);
        selecaoAtivo.setText("Ativo");

        botaoIncluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoIncluir.setText("Incluir");
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });

        botaoExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoEditar.setText("Editar");

        botaoSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoSair.setText("Sair");

        botaoLimpar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        tabelaCategorias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabelaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCategorias.setRowHeight(30);
        tabelaCategorias.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        tabelaCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCategoriasMouseClicked(evt);
            }
        });
        rolagemCategorias.setViewportView(tabelaCategorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rolagemCategorias)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotuloCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoSair))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rotuloNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selecaoAtivo)
                                    .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 153, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoEditar, botaoExcluir, botaoIncluir, botaoLimpar, botaoSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloCodigo)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloNome)
                    .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selecaoAtivo)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoIncluir)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoEditar)
                    .addComponent(botaoSair)
                    .addComponent(botaoLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rolagemCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limpar() {
        textoCodigo.setText(null); // Limpa o campo de código
        textoNome.setText(null); // Limpa o campo de nome
        selecaoAtivo.setSelected(true); // Marca o checkbox como selecionado por padrão
        
        textoNome.requestFocus(); // Coloca o foco de volta no campo de nome para facilitar o próximo cadastro
    }
    
    private void listar() {
        List<Categoria> lista = DB // Inicia a consulta no banco de dados
                .find(Categoria.class) // Busca todas as instâncias da classe Categoria
                .where() // Adiciona uma cláusula WHERE
                    .eq("ativo", true) // Filtra apenas as categorias onde o campo "ativo" é igual a true
                .orderBy("nome") // Ordena os resultados pelo nome
                .findList(); // Finaliza a consulta e retorna a lista

        DefaultTableModel modelo = (DefaultTableModel) tabelaCategorias.getModel(); // Obtém o modelo da tabela de categorias

        modelo.setRowCount(0); // Limpa todas as linhas atuais da tabela

        for (Categoria categoria : lista) { // Percorre cada categoria da lista
            modelo.addRow( // Adiciona uma nova linha à tabela
                    new Object[]{ // Cria um array de objetos para representar a linha
                        categoria.getCodigo(), // Primeira coluna: código da categoria
                        categoria.getNome(), // Segunda coluna: nome da categoria
                        categoria.getAtivo() ? "Sim" : "Não" // Terceira coluna: status da categoria
                    }
            );
        }
    }
    
    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed
        Categoria categoria = new Categoria(); // Cria uma nova instância de Categoria
        categoria.setNome(textoNome.getText()); // Define o nome da categoria com o texto inserido pelo usuário
        categoria.setAtivo(selecaoAtivo.isSelected()); // Define se a categoria está ativa com base na seleção do checkbox

        categoria.save(); // Salva a categoria no banco de dados

        listar(); // Atualiza a tabela com a lista de categorias ativas ordenadas pelo nome
        limpar(); // Limpa os campos do formulário e define valores padrão para iniciar um novo cadastro

        JOptionPane.showMessageDialog(this, "Categoria inserida com sucesso!", "Categorias", JOptionPane.INFORMATION_MESSAGE); // Exibe uma mensagem informando que a categoria foi inserida com sucesso
    }//GEN-LAST:event_botaoIncluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listar(); // Atualiza a tabela com a lista de categorias ativas ordenadas pelo nome
        limpar(); // Limpa os campos do formulário e define valores padrão para iniciar um novo cadastro
    }//GEN-LAST:event_formWindowOpened

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        listar(); // Atualiza a tabela com a lista de categorias ativas ordenadas pelo nome
        limpar(); // Limpa os campos do formulário e define valores padrão para iniciar um novo cadastro
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void tabelaCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCategoriasMouseClicked
        int linhaSelecionada = tabelaCategorias.getSelectedRow(); // Obtém o índice da linha selecionada na tabela `tabelaCategorias`.

        if (linhaSelecionada != -1) { // Verifica se uma linha foi realmente selecionada (índice diferente de -1).
            textoCodigo.setText(tabelaCategorias.getValueAt(linhaSelecionada, 0).toString()); // Define o texto do campo `textoCodigo` com o valor da célula da primeira coluna (índice 0) da linha selecionada.
            textoNome.setText(tabelaCategorias.getValueAt(linhaSelecionada, 1).toString()); // Define o texto do campo `textoNome` com o valor da célula da segunda coluna (índice 1) da linha selecionada.
            selecaoAtivo.setSelected(tabelaCategorias.getValueAt(linhaSelecionada, 2).toString().equals("Sim")); // Define o estado do checkbox `selecaoAtivo` como selecionado se o valor da célula da terceira coluna (índice 2) da linha selecionada for "Sim".
        }
    }//GEN-LAST:event_tabelaCategoriasMouseClicked

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        if (textoCodigo.getText().isEmpty()) { // Verifica se o campo de texto 'textoCodigo' está vazio.
            JOptionPane.showMessageDialog(this, "O campo código é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE); // Exibe uma mensagem de aviso ao usuário informando que o campo código é obrigatório.
            return; // Interrompe a execução do método caso o campo esteja vazio.
        }

        Categoria categoria = DB.find( // Busca no banco de dados uma entidade da classe 'Categoria' com o ID fornecido.
                Categoria.class, // Especifica a classe da entidade que será buscada.
                Integer.valueOf(textoCodigo.getText()) // Converte o valor do campo 'textoCodigo' para um inteiro, que será usado como ID.
        );

        categoria.setAtivo(false); // Define o atributo 'ativo' da categoria como 'false', desativando-a.
        categoria.update(); // Atualiza a entidade no banco de dados com a alteração realizada.

        listar(); // Atualiza a tabela com a lista de categorias ativas ordenadas pelo nome
        limpar(); // Limpa os campos do formulário e define valores padrão para iniciar um novo cadastro

        JOptionPane.showMessageDialog(this, "Categoria removida com sucesso!", "Categorias", JOptionPane.INFORMATION_MESSAGE); // Exibe uma mensagem informando ao usuário que a categoria foi removida com sucesso.
    }//GEN-LAST:event_botaoExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CategoriaForm dialog = new CategoriaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoIncluir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JScrollPane rolagemCategorias;
    private javax.swing.JLabel rotuloCodigo;
    private javax.swing.JLabel rotuloNome;
    private javax.swing.JCheckBox selecaoAtivo;
    private javax.swing.JTable tabelaCategorias;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoNome;
    // End of variables declaration//GEN-END:variables
}
