INSERT INTO categoria (nome, ativo) VALUES ('Eletrônicos', 1);
INSERT INTO categoria (nome, ativo) VALUES ('Roupas', 1);
INSERT INTO categoria (nome, ativo) VALUES ('Alimentos', 1);
INSERT INTO categoria (nome, ativo) VALUES ('Móveis', 0);
INSERT INTO categoria (nome, ativo) VALUES ('Brinquedos', 1);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Smartphone', 2500.00, 10, 1, 1);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Notebook', 4500.00, 5, 1, 1);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Tablet', 1800.00, 8, 1, 1);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Smartwatch', 900.00, 15, 1, 1);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Fone de Ouvido', 250.00, 20, 1, 1);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Camiseta', 50.00, 30, 1, 2);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Calça Jeans', 120.00, 25, 1, 2);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Tênis', 250.00, 18, 1, 2);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Jaqueta', 300.00, 10, 1, 2);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Boné', 40.00, 35, 1, 2);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Smartphone', 2500.00, 10, 1, 1);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Notebook', 4500.00, 5, 1, 1);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Tablet', 1800.00, 8, 1, 1);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Smartwatch', 900.00, 15, 1, 1);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Fone de Ouvido', 250.00, 20, 1, 1);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Camiseta', 50.00, 30, 1, 2);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Calça Jeans', 120.00, 25, 1, 2);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Tênis', 250.00, 18, 1, 2);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Jaqueta', 300.00, 10, 1, 2);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Boné', 40.00, 35, 1, 2);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Arroz', 25.00, 50, 1, 3);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Feijão', 10.00, 45, 1, 3);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Macarrão', 8.00, 40, 1, 3);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Óleo de Soja', 12.00, 35, 1, 3);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Açúcar', 15.00, 38, 1, 3);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Sofá', 2000.00, 3, 0, 4);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Mesa de Jantar', 1500.00, 5, 1, 4);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Cadeira', 300.00, 15, 1, 4);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Guarda-Roupa', 2500.00, 4, 1, 4);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Cama Box', 1800.00, 6, 1, 4);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Boneca', 80.00, 20, 1, 5);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Carrinho de Controle Remoto', 150.00, 15, 1, 5);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Quebra-Cabeça', 50.00, 25, 1, 5);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Lego', 300.00, 12, 1, 5);
INSERT INTO produto (nome, preço, quantidade, ativo, categoria_codigo) VALUES ('Pelúcia', 100.00, 18, 1, 5);